'use strict'

// Error enumeration
module.exports = {
	NONE: 0,
	NOT_IN_CHANNEL: 1,
	NO_SUCH_CHANNEL: 2,
	STATIC_CHANNEL: 3,
	DUPLICATE_CHANNEL: 4,
	INVALID_CHANNEL_NAME: 5,
	INVALID_COMMAND_SYNTAX: 6,
	UNKNOWN_COMMAND: 7,
	INVALID_USERNAME: 8,
	DUPLICATE_USERNAME: 9
}
